<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxTable extends Doctrine_Table
{
  public function getTotalTaxesValue($tax_ids = array())
  {
    $result = 0;
    $taxes = $this->createQuery()
      ->whereIn('id',$tax_ids)
      ->execute();
    foreach($taxes as $tax)
    {
      $result += $tax->getValue();
    }
    return $result;
  }
}