<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Template extends BaseTemplate
{
  /**
   * Returns true if this is the default template
   *
   * @return boolean
   * @author Carlos Escribano <carlos@markhaus.com>
   **/
  public function isDefault()
  {
    return (!$this->isNew() && ($this->id == PropertyTable::get('default_template', null)));
  }
}