all:
  urls:
    variables:
      deleteTemplate:       configuration/deleteTemplate
      addNewNameValueItem:  configuration/addNewNameValueItem
      getCountries:         configuration/ajaxGetCountries