all:
  version:  0.3.4

  .culture:
    currency_decimals:  { BHD: 3, IQD: 3, JOD: 3, KWD: 3, LYD: 3, OMR: 3, TND: 3, BIF: 0, BYR: 0, CLP: 0, DJF: 0, HUF: 0, ISK: 0, JPY: 0, KMF: 0, KRW: 0, MGA: 0, PYG: 0, RWF: 0, VUV: 0, XPF: 0 }

  .listings:
    dashboard_max_results:    5
    pagination_max_results:   10
    notification_timeout:     10000

  sfDateTimePlugin:
    format_database: "%Y-%m-%d %H:%M:%S"

  sf_guard_plugin:
    remember_cookie_name:  SiwappRememberMe
    success_signin_url:    @dashboard
    success_signout_url:   @dashboard
    password_min_length:   4

  .css:
    semantics:
      forbidden:
        modules: ['sfguardauth']
        actions: ['index']

